runtime: python27
api_version: 1
threadsafe: true
application: sohil-blog

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: website.app

libraries:
- name: jinja2
  version: latest


  
